name: build

on: [push, pull_request, workflow_dispatch]

env:
  NAME:  NAudio.Vorbis
  NUGET: NAudio.Vorbis.Latest
  CONFIG: Release
  BIN_POSTFIX: .Bin
  RETENTION_DAYS: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    # Check out

    - name: Check out ${{env.NAME}}
      uses: actions/checkout@v4.2.2

    # Build

    - name: Build ${{env.NAME}} ${{env.CONFIG}}
      run: dotnet build --configuration ${{env.CONFIG}}

    # Upload artifacts

    - name: Publish ${{env.NAME}} ${{env.CONFIG}}
      uses: actions/upload-artifact@v4.6.0
      with:
        name: ${{env.NUGET}}${{env.BIN_POSTFIX}}
        path: ${{env.NAME}}/bin/${{env.CONFIG}}/${{env.NUGET}}.*.*nupkg
        retention-days: ${{env.RETENTION_DAYS}}
